version: '3.8'

services:
  # NestJS Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobio-backend
    restart: unless-stopped
    env_file:
      - ./config/.env
    environment:
      NODE_ENV: development
      DD_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 