export const ProfilesDiToken = {
  USER_DETAILS_REPOSITORY: Symbol('USER_DETAILS_REPOSITORY'),
  CANDIDATE_PROFILE_REPOSITORY: Symbol('CANDIDATE_PROFILE_REPOSITORY'),
  RECRUITER_PROFILE_REPOSITORY: Symbol('RECRUITER_PROFILE_REPOSITORY'),
  CREATE_USER_PROFILE_USE_CASE: Symbol('CREATE_USER_PROFILE_USE_CASE'),
  GET_USER_PROFILE_USE_CASE: Symbol('GET_USER_PROFILE_USE_CASE'),
  UPDATE_CANDIDATE_PROFILE_USE_CASE: Symbol('UPDATE_CANDIDATE_PROFILE_USE_CASE'),
  UPDATE_RECRUITER_PROFILE_USE_CASE: Symbol('UPDATE_RECRUITER_PROFILE_USE_CASE'),
} as const; 