export const CategoriesDiToken = {
  GET_ALL_CATEGORIES_USE_CASE: Symbol('GET_ALL_CATEGORIES_USE_CASE'),
  GET_ALL_SUB_CATEGORIES_USE_CASE: Symbol('GET_ALL_SUB_CATEGORIES_USE_CASE'),

  GET_CATEGORY_BY_ID_USE_CASE: Symbol('GET_CATEGORY_BY_ID_USE_CASE'),
  GET_SUB_CATEGORY_BY_ID_USE_CASE: Symbol('GET_SUB_CATEGORY_BY_ID_USE_CASE'),

  GET_CATEGORY_BY_NAME_USE_CASE: Symbol('GET_CATEGORY_BY_NAME_USE_CASE'),
  GET_SUB_CATEGORY_BY_NAME_USE_CASE: Symbol('GET_SUB_CATEGORY_BY_NAME_USE_CASE'),

  GET_CATEGORIES_USE_CASE: Symbol('GET_CATEGORIES_USE_CASE'),
  GET_SUB_CATEGORIES_USE_CASE: Symbol('GET_SUB_CATEGORIES_USE_CASE'),

  CATEGORY_REPOSITORY: Symbol('CATEGORY_REPOSITORY'),
  SUB_CATEGORY_REPOSITORY: Symbol('SUB_CATEGORY_REPOSITORY'),

  GET_SUB_CATEGORIES_BY_CATEGORY_ID_USE_CASE: Symbol('GET_SUB_CATEGORIES_BY_CATEGORY_ID_USE_CASE'),
} as const;
